### PR TITLE
tecnick.com/tcpdf abandoned

### PR DESCRIPTION
**Pull request by yalg**
replace abandoned tecnick.com/tcpdf by new repo tecnickcom/tcpdf

### CODE REVIEW

**Comment by OwlyCode** [comment]
Thank you !

**Comment by zazoomauro** [comment]
@OwlyCode can you please provide us a new html2pdf release? something like 4.0.5

**Comment by OwlyCode** [comment]
Sure, I am currently travelling but will do so this week-end.

**Comment by OwlyCode** [comment]
@zazoomauro The version 4.0.5 is now live, let me know if you encounter any bug.

**Pull request merged**
